server:
  port: 8888

spring:
  application:
    name: server-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/home/drawdecs/Descargas/synopis/eval-synopsis-v2.0/server-properties/